= DynamixelArduino Library for Arduino =

 This library implement all the required operation to drive Dynamixel servo.T his library is divided in 3 classes : dxl, dxlAx, dxlMx. As Dynamixel use half duplex communication, a halfDuplexSerial object should be passed as a constructor argument.
 This could be achieved using the halfDuplexSerial lib (soft, usig only one wire, or hard, using Tx, Rx and dir pin)
 Limitations:
   - Baudrate is limited 57 600bps ~ 115 200bps for 16Mhz Arduino board with softHalfDuplexSerial, and ~ 400 000bps for 16Mhz Arduino board with hardHalfDuplexSerial
  - This library is non blocking, i.e. when a write or a read command occured, it will wait NOT the answer of the servo. The return value is a bool (true when transmit succeed, false if an error occured during transmit)

You can customize servo control by editing the DynamixelConfig.h file.
The librarie has been written and tested with AX-12 servo & MX-64R, it should work with other Dynamixel servos.

For more information about this library please visit us at
https://github.com/akira215/DynamixelArduino

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
